# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2926e2b78efb57ae1481fcbbeb2f6caa0cdfaba7b83e0825d90b60f2031df1d9c951994f97bc58035028095e42ac0f62f46e4eff964f330e4481a0f3ec2acae1

test:
  secret_key_base: 51a4ed410cdd524436e74731b2ebc99dd82c36878acac31f736b3d061015911f60201d6f2ac597628a94c9cdbe0fadde288fd14c92b7cfd50c8ae0b330bb386e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
